/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asistenciaapp;

import controladorasistencia.controladorEstudiantes;
import controladorasistencia.controladorasistencia;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.TblAsistencia;
import modelos.TblEspecialidad;
import modelos.TblEstudiantes;

/**
 *
 * @author ulqui
 */
public class FormAsistencia extends javax.swing.JFrame {

    /**
     * Creates new form FormAsistencia
     */
    public TblEstudiantes ais2[];
     public DefaultTableModel m;
     FormEstudiante abrirFormEstudiante = new FormEstudiante();
     public Date fecha = new Date();
     public String carnet;
     public int id=-1;
     public String buscarcarnet;
     public DefaultTableModel modelosP;
    public FormAsistencia() {
        initComponents();
        txtFecha.setText("Fecha: "+ new SimpleDateFormat("dd-MM-yyyy").format(fecha));
        cargardatos();
        cargardatosEstu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSeleccion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtasistencia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtBusquedaEstudiante = new javax.swing.JTextField();
        txtagregarestudiante = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonAsistio = new javax.swing.JRadioButton();
        jRadioAusente = new javax.swing.JRadioButton();
        btnGuardarAsistencia = new javax.swing.JToggleButton();
        txtFecha = new javax.swing.JLabel();
        jcEvento = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lblPrueba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        dtasistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dtasistencia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dtasistencia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dtasistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtasistenciaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtasistencia);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asistenciaapp/resources/imgs/Logo (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("TABLA DE ASISTENCIAS - SEMANA DE SISTEMAS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnactualizar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asistenciaapp/resources/imgs/iconmonstr-restore-lined-240.png"))); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asistenciaapp/resources/imgs/iconmonstr-trash-can-filled-240.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setMaximumSize(new java.awt.Dimension(140, 55));
        btneliminar.setPreferredSize(new java.awt.Dimension(140, 55));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        txtBusquedaEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaEstudianteActionPerformed(evt);
            }
        });
        txtBusquedaEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaEstudianteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaEstudianteKeyTyped(evt);
            }
        });

        txtagregarestudiante.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtagregarestudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asistenciaapp/resources/imgs/iconmonstr-friend-1-240.png"))); // NOI18N
        txtagregarestudiante.setText("Agregar Estudiante");
        txtagregarestudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtagregarestudiante.setFocusPainted(false);
        txtagregarestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagregarestudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtBusquedaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnactualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(txtagregarestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtBusquedaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtagregarestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        grupoSeleccion.add(jButtonAsistio);
        jButtonAsistio.setText("Asistio");
        jButtonAsistio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButtonAsistioStateChanged(evt);
            }
        });

        grupoSeleccion.add(jRadioAusente);
        jRadioAusente.setText("Ausente");
        jRadioAusente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioAusenteStateChanged(evt);
            }
        });

        btnGuardarAsistencia.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnGuardarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asistenciaapp/resources/imgs/iconmonstr-window-plus-filled-240.png"))); // NOI18N
        btnGuardarAsistencia.setText("Guardar asistencia");
        btnGuardarAsistencia.setPreferredSize(new java.awt.Dimension(140, 55));
        btnGuardarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsistenciaActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtFecha.setText("Fecha");

        jcEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taller", "Ponencia" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnGuardarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAsistio)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jRadioAusente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAsistio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioAusente)
                            .addComponent(jcEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGuardarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jButton1.setText("Abrir form de asistencia por evento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPrueba)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dtasistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtasistenciaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dtasistenciaMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        id = dtasistencia.getRowCount();
        carnet = jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn()).toString();  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormEsta esta = new FormEsta();
        esta.setVisible(true);
        esta.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtagregarestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagregarestudianteActionPerformed
        // TODO add your handling code here:

        abrirFormEstudiante.setVisible(true);
        abrirFormEstudiante.setLocationRelativeTo(null);
        m=abrirFormEstudiante.mo;
    }//GEN-LAST:event_txtagregarestudianteActionPerformed

    private void txtBusquedaEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaEstudianteKeyTyped
        // TODO add your handling code here:
        //char c= evt.getKeyChar();
        //if ((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_txtBusquedaEstudianteKeyTyped

    private void txtBusquedaEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaEstudianteKeyReleased

        
        buscar(txtBusquedaEstudiante.getText());

    }//GEN-LAST:event_txtBusquedaEstudianteKeyReleased

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        cargardatosEstu();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnGuardarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsistenciaActionPerformed
        // TODO add your handling code here:
        String eve;
        eve = jcEvento.getSelectedItem().toString();
        lblPrueba.setText(eve);
        if (id > -1) {
         boolean asistioa = true;
        if(jButtonAsistio.isSelected()){
            asistioa = true;
            jcEvento.setEnabled(asistioa);
        }else if(jRadioAusente.isSelected()){
            asistioa = false;
            jcEvento.setEnabled(asistioa);
        }
        TblAsistencia asis = new TblAsistencia();
        asis.setIdasistencia(id);

        asis.setCarnetestudiante(ais2[jTable1.getSelectedRow()]);

        asis.setFechaasistencia(fecha);
        asis.setAsistio(asistioa);
        asis.setEvento(eve);

        Calendar calendario = Calendar.getInstance();
        int dia  = calendario.get(Calendar.DAY_OF_WEEK);
        asis.setDiasemana(diaSemana(dia));
        controladorasistencia cn = new controladorasistencia();
        cn.insertarAsistencia(asis);
        cargardatos();   
        }else
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
        id = -1;
    }//GEN-LAST:event_btnGuardarAsistenciaActionPerformed

    private void jRadioAusenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioAusenteStateChanged
        // TODO add your handling code here:
        if(jRadioAusente.isSelected()){
            jcEvento.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioAusenteStateChanged

    private void jButtonAsistioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButtonAsistioStateChanged
        // TODO add your handling code here:
        if(jButtonAsistio.isSelected()){
            jcEvento.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAsistioStateChanged

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        
        
        if (!"".equals(carnet)) {
            controladorEstudiantes cn = new controladorEstudiantes();
            cn.eliminarDato(carnet);
        }else
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtBusquedaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaEstudianteActionPerformed

    
    //METODO PARA BUSCAR ESTUDIANTES
    
     public void buscar(String nombres){
    
         listar(nombres);
         
    }
     
     //METODO PARA LISTAR ESTUDIANTES
          public void listar(String nombres){
     
         DefaultTableModel model;
         controladorEstudiantes cn = new controladorEstudiantes();
         String []columnas={"Carnet","Nombre","Especialidad", "Año Carrera"};
         model= new DefaultTableModel(null,columnas);
         
         List<TblEstudiantes> dt= cn.buscarEstudiantes(nombres);
         String [] datos= new String[4];
         for(TblEstudiantes te: dt){
         
        TblEspecialidad itemes = te.getCodigocarrera();
        datos[1]= te.getNombreestudiante()+""; 
        datos[0]= te.getCarnetestudiante()+"";
        datos[2]= itemes.getNombrecarrera()+"";
        datos[3] = te.getAnio_carrera()+"";
         
         model.addRow(datos);
         
         } 
         
         jTable1.setModel(model);
     }
          
          
          
          //METODO PARA BUSCAR ASISTENCIA
     
          
            public void listarasistencia(String busqueda){
     
         DefaultTableModel model;
         controladorasistencia ca= new controladorasistencia();
         String []columnas={"ID","Nombre","Carnet","Fecha","Asistio","Dia","Evento"};
         model= new DefaultTableModel(null,columnas);
         
         List<TblAsistencia> dt= ca.buscarPorAsistencia(busqueda);
         String [] datos= new String[7];
         for(TblAsistencia te: dt){
        TblEstudiantes it= te.getCarnetestudiante();
        datos[0]= te.getIdasistencia()+""; 
        datos[1]=it.getNombreestudiante()+"";
        datos[2]= it.getCarnetestudiante()+"";
        datos[3]= te.getFechaasistencia()+"";
        datos[4]=te.getAsistio()+"";
        datos[5]=te.getDiasemana()+"";
        datos[6] = te.getEvento()+"";
         
         model.addRow(datos);
         
         } 
         
         dtasistencia.setModel(model);
     }
          
          
            public void buscarasitencia(String carnet){
            
           listarasistencia(carnet);
            }
          
          
          
          
          
    
    //METODO PARA CARGAR DATOS ESTUDIANTES
    public void cargardatos(){
    
    DefaultTableModel modelo= new DefaultTableModel();
    
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    modelo.addColumn("ID");
    modelo.addColumn("Carnet");
    modelo.addColumn("Fecha");
    modelo.addColumn("Asistio");
    modelo.addColumn("Dia");
    modelo.addColumn("Evento");
    dtasistencia.setModel(modelo);
    controladorasistencia ca=new controladorasistencia();
    List<TblAsistencia> list = ca.getListAsistencia();
    String asistencia[] = new String[6];
    
    for(TblAsistencia item : list){
        String AsitioString;
        String fecha;
        fecha = format.format(item.getFechaasistencia());
        TblEstudiantes itemAsis = item.getCarnetestudiante();
        TblEspecialidad itemes = itemAsis.getCodigocarrera();
        if(item.getAsistio()){
            AsitioString = "Si";
        } else {
            AsitioString = "No";
        }
        asistencia[0]= item.getIdasistencia().toString();
        asistencia[1]= itemAsis.getCarnetestudiante();
        asistencia[2]= fecha;
        asistencia[3] = AsitioString;
        asistencia[4] = item.getDiasemana();
        asistencia[5] = item.getEvento();
        modelo.addRow(asistencia);
    }
    dtasistencia.setModel(modelo);
    }
    
    //METODO PARA CARGAR DATOS ESTUDIANTES
    
    public void cargardatosEstu(){
    DefaultTableModel modelo= new DefaultTableModel();
    int i = 0;
    modelo.addColumn("Carnet");
    modelo.addColumn("Nombre");
    modelo.addColumn("Carrera");
    modelo.addColumn("Año Carrera");

    controladorEstudiantes ca=new controladorEstudiantes();
    List<TblEstudiantes> list = ca.getListEstudiantes();
    ais2 = new TblEstudiantes[list.size()];
    String estudi[] = new String[4];
    for(TblEstudiantes item : list){
        TblEspecialidad itemes = item.getCodigocarrera();
        estudi[0] = item.getCarnetestudiante();
        estudi[1]= item.getNombreestudiante();
        estudi[2] = itemes.getNombrecarrera();
        estudi[3] = item.getAnio_carrera();
        ais2[i] = item;
        i++;
        modelo.addRow(estudi);
    }
    
    if(m!= null){
    
    jTable1.setModel(m);
    }else{
    
     jTable1.setModel(modelo);
    }
    

    }
    public String diaSemana(int dia){
        if(dia == 5){
           return "Jueves"; 
        }else if(dia ==6){
            return "Viernes"; 
        }else if(dia==7){
            return "Sabado"; 
        }else if(dia == 1){
            return "Domingo"; 
        }else if(dia == 2){
            return "Lunes"; 
        }else if(dia == 3){
            return "Martes"; 
        }else if(dia == 4){
            return "Miercoles"; 
        }
        return ""; 
    }
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGuardarAsistencia;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JTable dtasistencia;
    private javax.swing.ButtonGroup grupoSeleccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jButtonAsistio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioAusente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcEvento;
    private javax.swing.JLabel lblPrueba;
    private javax.swing.JTextField txtBusquedaEstudiante;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JButton txtagregarestudiante;
    // End of variables declaration//GEN-END:variables
}
