/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asistenciaapp;

import controladorasistencia.controladorEstudiantes;
import controladorasistencia.controladorasistencia;
import controladorasistencia.controladorlistado;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.TblAsistencia;
import modelos.TblEspecialidad;
import modelos.TblEstudiantes;

/**
 *
 * @author Diego
 */
public class FormEsta extends javax.swing.JFrame {

    /**
     * Creates new form FormEsta
     */
    TableRowSorter<DefaultTableModel> sorter;
    String seleccion = "-";
    public FormEsta() {
        initComponents();
        cargardatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        asi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jcAnio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        asi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(asi);

        jLabel1.setText("Asistencia ordenada por evento");

        jLabel3.setText("Busqueda por Evento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Ponencia", "Taller" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jcAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1° Año", "2° Año", "3° Año", "4° Año", "5° Año" }));
        jcAnio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcAnioItemStateChanged(evt);
            }
        });

        jLabel2.setText("Año de carrera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel1)
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        seleccion = jComboBox1.getSelectedItem().toString();
//        controladorlistado cl= new controladorlistado();
        if( seleccion == "Ponencia")
        {
             listarasistencia(seleccion);
    
        }
        else if(seleccion == "Taller")
        {
              listarasistencia(seleccion);
        }
        else if(seleccion == "-")
        {
            cargardatos();
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jcAnioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcAnioItemStateChanged
        // TODO add your handling code here:
         String selAnio = jcAnio.getSelectedItem().toString();
         if(selAnio != "-"){
             filtrar(selAnio);
         }else if(selAnio == "-" && seleccion != "-"){
             listarasistencia(seleccion);
         }else if(selAnio == "-" && seleccion == "-"){
             cargardatos();
         }
         
    }//GEN-LAST:event_jcAnioItemStateChanged

    
    public void filtrar(String a){
        try {
            sorter.setRowFilter(RowFilter.regexFilter(a));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
     
     public void listarasistencia( String seleccion){
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
         DefaultTableModel model;
         String []columnas={"ID","Nombre","Carnet","Año carrera","Fecha","Asistio","Dia","Evento"};
         model= new DefaultTableModel(null,columnas);
         controladorlistado cl= new controladorlistado();
         
         List<TblAsistencia> dt= cl.buscarPorParametro(seleccion);
         String [] datos= new String[8];
         for(TblAsistencia te: dt){
        TblEstudiantes it= te.getCarnetestudiante();
        String fecha;
        fecha = format.format(te.getFechaasistencia());
        datos[0]= te.getIdasistencia()+""; 
        datos[1]=it.getNombreestudiante()+"";
        datos[2]= it.getCarnetestudiante()+"";
        datos[3] = it.getAnio_carrera()+"";
        datos[4]= fecha;
        datos[5]=te.getAsistio()+"";
        datos[6]=te.getDiasemana()+"";
        datos[7] = te.getEvento()+"";
         
         model.addRow(datos);
         
         } 
         
         asi.setModel(model);
         asi.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        asi.setRowSorter(sorter);
     }
     
     
    
    
    
    
    
     public void cargardatos(){
    
    DefaultTableModel modelo= new DefaultTableModel();
    
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    modelo.addColumn("ID");
     modelo.addColumn("Nombre");
    modelo.addColumn("Carnet");
    modelo.addColumn("Año carrera");
    modelo.addColumn("Fecha");
    modelo.addColumn("Asistio");
    modelo.addColumn("Dia");
    modelo.addColumn("Evento");
    asi.setModel(modelo);
    controladorasistencia ca=new controladorasistencia();
    List<TblAsistencia> list = ca.getListAsistencia();
    String asistencia[] = new String[8];
    
    for(TblAsistencia item : list){
        String AsitioString;
        String fecha;
        fecha = format.format(item.getFechaasistencia());
        TblEstudiantes itemAsis = item.getCarnetestudiante();
        TblEspecialidad itemes = itemAsis.getCodigocarrera();
        if(item.getAsistio()){
            AsitioString = "Si";
        } else {
            AsitioString = "No";
        }
        asistencia[0]= item.getIdasistencia().toString();
        asistencia[1]=itemAsis.getNombreestudiante();
        asistencia[2]= itemAsis.getCarnetestudiante();
        asistencia[3] = itemAsis.getAnio_carrera();
        asistencia[4]= fecha;
        asistencia[5] = AsitioString;
        asistencia[6] = item.getDiasemana();
        asistencia[7] = item.getEvento();
        modelo.addRow(asistencia);
    }
    asi.setModel(modelo);
    asi.setAutoCreateRowSorter(true);
    sorter = new TableRowSorter<>(modelo);
    asi.setRowSorter(sorter);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEsta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEsta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEsta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEsta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEsta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable asi;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcAnio;
    // End of variables declaration//GEN-END:variables
}
